version: '3.7'

services:
  sparql_editor_fe:
    container_name: sparql_editor_fe
    image: andrejpopordanoski/sparql-editor:fe
    # build:
    #   context: ./sparql_editor_fe
    #   dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    networks:
      - frontend

  sparql_editor_be:
    container_name: sparql_editor_be
    image: andrejpopordanoski/sparql-editor:be
    # build:
    #   context: sparql_editor_be
    #   dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SparqlEditor?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Skopje
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: aplikacija
    networks:
      - backend
      - frontend

  db:
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: SparqlEditor
      MYSQL_USER: username
      MYSQL_PASSWORD: aplikacija
      MYSQL_ROOT_PASSWORD: aplikacija
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
  frontend:
