version: '3.7'

services:
  # sparql_editor_fe:
  #   container_name: sparql_editor_fe
  #   build:
  #     context: ./sparql_editor_fe
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  sparql_editor_fe:
    container_name: sparql_editor_fe
    build:
      context: ./sparql_editor_fe
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
    networks:
      - frontend

  sparql_editor_be:
    container_name: sparql_editor_be
    build:
      context: sparql_editor_be # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SparqlEditor?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Skopje
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: aplikacija
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  db:
    image: mysql
    ports:
      - '3306:3306'
    # command: --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: SparqlEditor
      MYSQL_USER: username
      MYSQL_PASSWORD: aplikacija
      MYSQL_ROOT_PASSWORD: aplikacija
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
  frontend:
